spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: aux12mar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
